### PR TITLE
If units = stems, changed to inspect per stem

### PR DESCRIPTION
**Pull request by kellynm**
Using n_units_to_inspect instead of always converting to n_boxes_to_inspect.

### CODE REVIEW

**Comment by kellynm** [comment]
@wenzeslaus This should be working now to inspect by stem. I haven't tried to break it, but it is behaving as expected for the scenarios I tested.

**Comment by wenzeslaus** [comment]
@kellynm Will you work on this right now or do you want to me to just fix the conflict in `inspections.py`? (I would do it here on GitHub.)

**Comment by kellynm** [comment]
If it's an easy fix, please go ahead and do it. I'll start on the other
branch to add the partial box inspections. Please let me know if you need
me to address anything. Thank you!

**Comment by wenzeslaus** [comment]
Thanks to the merge, it is now also using the tests from scenarios (and makes use of completely fixed CI and issues fixed here). However, it does not work for the scenario test (`total_stems_inspected_completion` seems to be zero):

```
             pct_sample_if_to_detection=(
>               (total_stems_inspected_detection / total_stems_inspected_completion) * 100
            ),
            pct_pest_unreported_if_detection=pct_pest_unreported_if_detection,
            true_infestation_rate=true_infestation_rate / num_shipments,
            missed_infestation_rate=missed_infestation_rate,
            intercepted_infestation_rate=intercepted_infestation_rate,
            false_negative_present=false_negative_present,
            true_positive_present=true_positive_present,
        )
E       ZeroDivisionError: division by zero
```

**Comment by kellynm** [comment]
@wenzeslaus Can you tell which scenario this is for, or is it all of them? When I run it on the command line, number of stems inspected to completion is non-zero.

**Comment by wenzeslaus** [comment]
Not from the current output, but it might be easy to get, I think if you put a print in the for loop in run_scenarios(), the last printed should be the offending one.

**Comment by wenzeslaus** [comment]
This needed the same changes which were in 557197e84105a9f89b4a2ca7181bbdd8a7294a74 in merge here (54eb19d0b4b2fb6342d5fdaea6276fc488ed8a89 on master branch): The CSV from #60 had unit(s) as singular (box, stem), but the code expected plural. It seemed reasonable to me to support both, so I added that to sample functions. This new inspect() function needed the same addition. I also added some error handling to check for an invalid input rather than ignoring that case. In light of the problems, I wonder now if requiring one or the other isn't safer and thus better, but the problem was really the missing check for the error state, so perhaps supporting both singular and plural is not such a big burden after all.

**Comment by kellynm** [comment]
@wenzeslaus were you able to tell which scenarios caused the divide by zero error? or was that related to the stem vs. stems issue?

**Comment by wenzeslaus** [comment]
It was the first one, or all to be exact. The problem was that the CSV has "box" and "stem" while the code had "boxes" and "stems" as a unit. The code in inspect() did not check for an invalid unit and left the defaults (zeros) in the result which then happily returned.

**Pull request closed without merging**
