### PR TITLE
Update names in scenario and validation notebooks, add all to CI

### PR DESCRIPTION
**Pull request by wenzeslaus**
Uses PNGs as output instead of SVGs.

Now some scenarios generate:
Warning: Within box proportion is too low and/or interval is too high to achieve sample size. Automatically increasing within box proportion to achieve sample size.

This mostly updates to new names, but it removes one local CSV loading cell and last empty cell.

### CODE REVIEW

**Comment by wenzeslaus** [comment]
The most relevant part of the diff (generated by nbdiff) is:

```diff
## modified /cells/4/source:
@@ -7,28 +7,28 @@ df = save_scenario_result_to_pandas(
         "consignment/boxes/min",
         "consignment/boxes/max",
         "consignment/items_per_box/default",
-        "contamination/infestation_rate/parameters",
+        "contamination/contamination_rate/parameters",
         "contamination/arrangement",
         "inspection/unit",
         "inspection/sample_strategy",
-        "inspection/percentage/proportion",
+        "inspection/proportion/value",
         "inspection/hypergeometric/detection_level",
         "inspection/selection_strategy",
         "inspection/within_box_pct",
-        "inspection/hierarchical/outer",
+        "inspection/cluster/cluster_selection",
     ],
     result_columns=[
         "missing",
-        "true_infestation_rate",
-        "max_missed_infestation_rate",
-        "avg_missed_infestation_rate",
-        "max_intercepted_infestation_rate",
-        "avg_intercepted_infestation_rate",
+        "true_contamination_rate",
+        "max_missed_contamination_rate",
+        "avg_missed_contamination_rate",
+        "max_intercepted_contamination_rate",
+        "avg_intercepted_contamination_rate",
         "avg_boxes_opened_completion",
         "avg_boxes_opened_detection",
         "avg_items_inspected_completion",
         "avg_items_inspected_detection",
-        "pct_sample_if_to_detection",
-        "pct_contaminants_unreported_if_detection",
+        "pct_items_inspected_detection",
+        "pct_contaminant_unreported_if_detection",
     ],
 )
```

@kellynm The notebook had `pct_contaminants_...` while the name in the package is `pct_contaminant_...` Is plural or singular better here?

**Comment by kellynm** [comment]
I added to warning to notify user that the simulation is recomputing proportion to sample within boxes on the fly. It confused me when I looked at the visualizations and saw it was sampling more than I put in the configuration, so I figured it would be good to warn others of this.

Plural might sound better, but I changed to singular to fit this all on one line:
pct_contaminant_unreported_if_detection=pct_contaminant_unreported_if_detection,

Either way is ok with me.

**Comment by wenzeslaus** [comment]
> I added to warning to notify user that the simulation is recomputing proportion to sample within boxes on the fly.

+1 I was just wondering if it was expected here, so I'm leaving it as is. Thanks.

> Plural might sound better, but I changed to singular to fit this all on one line:
> pct_contaminant_unreported_if_detection=pct_contaminant_unreported_if_detection,

Okay, leaving as is.

**Comment by wenzeslaus** [comment]
`validation_plots.ipynb` runs a long time, so I included it in a separate job in CI. Now all notebooks run automatically in CI and I manually tested them with Binder.

**Pull request merged**
